[versions]
kotlin = "2.1.21"
shadow = "8.1.1"
clikt = "5.0.3"
koogAgents = "0.2.1"

[libraries]
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
koog-agents = { module = "ai.koog:koog-agents", version.ref = "koogAgents" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
